[General]
layerDock=false
moleculeDock=false
recentFiles=@Invalid()
sceneDock=false
toolDock=false
viewDock=false

[MainWindow]
BallStick=true
Cartoons=true
CloseContacts=false
CrystalScene=false
Dipole=false
Force=false
Label=false
Licorice=false
Meshes=false
NonCovalent=false
QTAIMScenePlugin=false
SymmetryScene=true
VanDerWaals=false
Wireframe=false
lastOpenDir=/home/gyom/Documents/Sciences/psi4_comput
lastSaveDir=/home/gyom/Documents/Sciences/psi4_comput
perspective=true
pos=@Point(6 30)
size=@Size(628 684)

[autoopt]
method=UFF

[editortool]
userElements=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\x2\0\0\0\\)

[overlayAxes]
enabled=true

[quantumInput]
Psi\outputDirectory=/home/gyom/Documents/Sciences/psi4_comput

[templatetool]
ligandType=0
